version: "3.7"

services:

  db:
    image: postgres
    restart: always
    container_name: practice_db
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres