server:
  servlet:
    context-path: /user-srv

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: postgres
  liquibase:
    drop-first: false